In [1]:
import os
for dirname, _, filenames in os.walk('C:/Users/VIGHNESHBALAJI/Desktop/archive'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

C:/Users/VIGHNESHBALAJI/Desktop/archive\1429_1.csv
C:/Users/VIGHNESHBALAJI/Desktop/archive\Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products.csv
C:/Users/VIGHNESHBALAJI/Desktop/archive\Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products_May19.csv

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import string
import math
import spacy
from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud
from textwrap import wrap
from textblob import TextBlob

In [9]:
import textstat

In [10]:
text=pd.read_csv('C:/Users/VIGHNESHBALAJI/Desktop/archive/1429_1.csv')

C:\Users\VIGHNESHBALAJI\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (1,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
text.shape

(34660, 21)

In [12]:
text.head()

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [13]:
text.columns

Index(['id', 'name', 'asins', 'brand', 'categories', 'keys', 'manufacturer',
       'reviews.date', 'reviews.dateAdded', 'reviews.dateSeen',
       'reviews.didPurchase', 'reviews.doRecommend', 'reviews.id',
       'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs',
       'reviews.text', 'reviews.title', 'reviews.userCity',
       'reviews.userProvince', 'reviews.username'],
      dtype='object')

In [14]:
textdata = text[['name','reviews.text','reviews.doRecommend','reviews.numHelpful']]
textdata.head()

,name,reviews.text,reviews.doRecommend,reviews.numHelpful
0,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",This product so far has not disappointed. My c...,True,0.0
1,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",great for beginner or experienced person. Boug...,True,0.0
2,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",Inexpensive tablet for him to use and learn on...,True,0.0
3,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",I've had my Fire HD 8 two weeks now and I love...,True,0.0
4,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",I bought this for my grand daughter when she c...,True,0.0

In [15]:
textdata.dropna(inplace=True)
textdata.isna().sum()

C:\Users\VIGHNESHBALAJI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

name                   0
reviews.text           0
reviews.doRecommend    0
reviews.numHelpful     0
dtype: int64

In [16]:
textcopy=textdata.copy()

In [17]:
#filtering data based on reviews
textdata=textdata.groupby(['name']).filter(lambda x: len(x)>300).reset_index(drop=True)
print('Number of products matching the criteria is ',len(textdata['name'].unique()))

Number of products matching the criteria is  10

In [18]:
#converting float to int
textdata['reviews.doRecommend']=textdata['reviews.doRecommend'].astype(int)
textdata['reviews.numHelpful']=textdata['reviews.numHelpful'].astype(int)

In [19]:
#cleaning text data
textdata['name'].unique()
textdata['name']=textdata['name'].apply(lambda x: x.split(',,,')[0])

In [20]:
#clean review text
for text in enumerate(textdata['reviews.text'][20:30]):
    print('Review:\n',text)

Review:
 (0, 'Excellent tablet with nice screen. I wish Amazon would pre install the play store, this would have been perfect.')
Review:
 (1, 'Preloaded with the reading app from Kindle but expandable with other apps. Perfect for travel. Carry your library, games and productivity apps in a small footprint.')
Review:
 (2, 'Very happy with this product and easy to use..picture is clear, takes great pictures..')
Review:
 (3, 'My grandchildren are home schooled and utilize the tables for many learning apps! They LOVE using them as it makes them feel "so grown up"! The tablets are a great leaning tool and they are receiving many benefits from them!')
Review:
 (4, 'Great size, easy to carry for traveling. Need to spend more time Looking into apps for contact manegement, interactive calenders and most important, music storage and use.')
Review:
 (5, 'I purchased this when my last tablet died. It meets all basic needs and the price was great.')
Review:
 (6, 'Perfect for downloading and reading books !! Perfect size and has a nice, bright screen.')
Review:
 (7, "I was surprised when I learned of the capabilities of this device. Now my husband has more access to his desktop and I am doing things which I couldn't on his device.")
Review:
 (8, 'I got it for my son. Its user friendly and durable.')
Review:
 (9, 'The visual quality on the Fire 8 HD is amazing. It runs very fast and is easy to use, very durable.')

In [21]:
#converting to lower case
textdata['reviews.text']=textdata['reviews.text'].apply(lambda x: x.lower())

In [22]:
#eliminating digits
textdata['reviews.text']=textdata['reviews.text'].apply(lambda x: re.sub('\w*\d\w*','', x))

In [23]:
#elim punctuations
textdata['reviews.text']=textdata['reviews.text'].apply(lambda x: re.sub('[%s]' % re.escape(string.punctuation), '', x))

In [29]:
spacy.load("en_core_web_sm")

In [30]:
#use of spacy models for piplining if text in NLP
nlp = spacy.load('en_core_web_sm',disable=['parser', 'ner'])

# stopwords removal and lemmatization
textdata['reviews.text']=textdata['reviews.text'].apply(lambda x: ' '.join([token.lemma_ for token in list(nlp(x)) if (token.is_stop==False)]))

textdata=textdata[['name','reviews.text']].groupby(by='name').agg(lambda x:' '.join(x))
textdata.head()

                                                                                         reviews.text
name
All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, ...  product far disappoint child love use like abi...
Amazon - Amazon Tap Portable Bluetooth and Wi-F...  love buy buy parent easy start walk right inst...
Amazon Fire Tv                                      echo learn everyday use daily use place speake...
Amazon Kindle Paperwhite - eBook reader - 4 GB ...  nice little set slow wish investigate little j...
Brand New Amazon Kindle Fire 16gb 7 Ips Display...  good value money hand work perfectly purchase ...

In [31]:
cv=CountVectorizer(analyzer='word')
data=cv.fit_transform(textdata['reviews.text'])
text_dtm = pd.DataFrame(data.toarray(), columns=cv.get_feature_names())
text_dtm.index=textdata.index
text_dtm.head()

,aa,aaa,aamazon,abandon,abattery,abc,abcmouse,abcmousecom,abd,ability,...,zero,zigbee,zinio,zip,zippy,zone,zoo,zoom,zooming,zwave
name,,,,,,,,,,,,,,,,,,,,,
"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 16 GB - Includes Special Offers, Magenta",0,0,0,0,0,0,0,0,0,24,...,4,0,1,0,0,0,0,0,0,0
Amazon - Amazon Tap Portable Bluetooth and Wi-Fi Speaker - Black,0,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
Amazon Fire Tv,0,1,1,0,0,0,0,0,0,37,...,0,0,0,1,0,0,0,0,0,0
Amazon Kindle Paperwhite - eBook reader - 4 GB - 6 monochrome Paperwhite - touchscreen - Wi-Fi - black,0,0,0,1,0,2,0,0,0,56,...,4,0,0,0,0,2,0,2,0,0
Brand New Amazon Kindle Fire 16gb 7 Ips Display Tablet Wifi 16 Gb Blue,0,0,0,0,0,1,0,0,0,6,...,0,0,0,0,0,0,0,0,0,0